title: WHATSYOURBLOGNAME
author: WriteNameHere
email: replace@gmail.com
url: 
baseurl: "/jekyll-theme"

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Disqus Comments
disqus:
  shortname: jekyll-theme



feeds:
  feedburner: jekyll-theme
  subscribe: jekyll-theme

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false

social_links:
  github: 
  twitter: 

plugins:
  - jekyll-gist
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-paginate
  - jemoji
